name: Update star count banner

on:
  # chạy mỗi 15 phút – đủ mới nhưng không đốt quota
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write # cho phép push

    steps:
      - uses: actions/checkout@v4

      # 1. Lấy số ⭐ với token mặc định
      - name: Get stargazer count
        id: stars
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          STAR=$(curl -s \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }} |
            jq -r '.stargazers_count')
          echo "stars=$STAR" >> "$GITHUB_OUTPUT"

      # 2. Ghi đè số trong thẻ <tspan id="starCount">…</tspan>
      - name: Patch SVG
        run: |
          sed -E -i \
            's/(<tspan[^>]*id="starCount">)[0-9,]*(<\/tspan>)/\1'"${{ steps.stars.outputs.stars }}"'\2/' \
            img/information.svg

      # 3. Commit nếu có thay đổi
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name  "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add img/information.svg
            git commit -m "ci: update star count → ${{ steps.stars.outputs.stars }}"
            git push
          fi
